import {
    Status,
    CompanyStatus,
    Phases,
    // Leads,
    LeadsTable,
    Candidates,
    Designations,
    ExposedCandidates,
    AssignCandidate,
    MyProfile,
    LeadNotes,
    ExposedTeams,
} from '@modules'

export const leadsRoutes = [
    {
        path: '/status',
        component: <Status />,
        protect: true,
        title: 'All Statuses',
        permission: 'view_status',
    },
    {
        path: '/company-status',
        component: <CompanyStatus />,
        protect: true,
        title: 'Status',
        permission: 'view_company_status',
    },
    {
        path: '/phases',
        component: <Phases />,
        protect: true,
        title: 'Phases',
        permission: 'view_phase',
    },
    {
        path: '/leads',
        component: <LeadsTable />,
        protect: true,
        title: 'My Leads',
        permission: 'view_lead',
    },
    {
        path: '/candidates',
        component: <Candidates />,
        protect: true,
        title: 'Candidates',
        permission: 'view_candidate',
    },
    {
        path: '/designations',
        component: <Designations />,
        protect: true,
        title: 'Designations',
        permission: 'view_designation',
    },
    {
        path: '/exposed-candidates',
        component: <ExposedCandidates />,
        protect: true,
        title: 'Exposed Candidates',
        permission: 'view_exposed_candidate',
    },
    {
        path: '/exposed-teams',
        component: <ExposedTeams />,
        protect: true,
        title: 'Exposed Teams',
        permission: 'view_exposed_candidate',
    },
    {
        path: '/assign-candidate/:id',
        component: <AssignCandidate />,
        protect: true,
        title: 'Assign / Re-Assign Candidate',
        permission: 'view_lead',
    },
    {
        path: '/my-profile',
        component: <MyProfile />,
        protect: true,
        title: 'My Profile',
        permission: 'view_candidate_profile',
    },
    {
        path: '/lead-notes/:id',
        component: <LeadNotes />,
        protect: true,
        title: 'Lead Notes',
        permission: 'view_lead',
    },
]
